#!/bin/bash

set -eux

export BASE_PIP_URL=`config-get pypi-index`

easy_install -i $BASE_PIP_URL -U pip

status-set waiting "donwloading latest install_rally.sh..." || juju-log "downloading install_rally.sh"
wget -q -O /tmp/install_rally.sh https://raw.githubusercontent.com/openstack/rally/master/install_rally.sh
chmod +x /tmp/install_rally.sh

status-set maintenance "running install_rally.sh..." || juju-log "running install_rally.sh"
/tmp/install_rally.sh -y

status-set maintenance "creating rally database" || juju-log "creating rally database"
rally-manage db recreate

status-set maintenance "installing benchmarking tools" || juju-log "installing benchmark tools"
pip install -i $BASE_PIP_URL charm-benchmark

if [ ! -f /root/.keystone_auth ]; then
  status-set blocked "need to be related to a keystone" || true
else
  status-set active "ready to benchmark" || true
fi
