#!/bin/bash

status-set waiting "waiting for Keystone credentials" || true

if [ -z "$(relation-get service_password)" ]; then
  exit 0;
fi

juju-log "$(relation-get --format=json)"

status-set maintenance "writing 'novarc' file" || true

cat > /root/.keystone_auth <<EOF
export OS_AUTH_URL=http://$(relation-get service_hostname):$(relation-get service_port)/v2.0
export OS_TENANT_NAME=$(relation-get service_tenant_name)
export OS_USERNAME=$(relation-get service_username)
export OS_REGION=$(relation-get service_region)
export OS_PASSWORD=$(relation-get service_password)
EOF

status-set active "ready to benchmark" || true
