options:
  mgmt-int:
    type: string
    default: "br-eth0"
    description: "Management interface for Cplane controller"
  cp-controller-mport:
    type: int
    default: 1901 
    description: "Cplane controller multicast port"
  cp-controller-uport:
    type: int
    default: 1902
    description: "Cplane controller unicast port"
  rabbit-user:
    type: string
    default: "neutron"
    description: "Neutron rabbit user name"
  rabbit-vhost:
    type: string
    default: "openstack"
    description: "Nova rabbit vhost"
  admin-user:
    type: string
    default: "nova"
    description: "Admin user"
  admin-password:
    type: string
    default: "nova"
    description: "Admin password"
  cplane-controller-ip:
    type: string
    default: "192.168.4.154"
    description: "Cplane-Controller IP"
  region:
    type: string
    default: "RegionOne"
    description: "Openstack region"
  data-interface:
    type: string
    default: "br-eth1"
    description: "Data interface to create the bridge network"
  data-gateway:
    type: string
    default:
    description: "Data network gateway if this cannot be configured in /etc/network/interfaces"
  tun-interface:
    type: string
    default: "br-eth2"
    description: "Interface to create the br-tun bridge"
  tun-gateway:
    type: string
    default: 192.168.7.254
    description: "Tunnel network gateway if this cannot be configured in /etc/network/interfaces"
  fip-interface:
    type: string
    default: "br-eth3"
    description: "Interface to create the br-fip bridge"
  cp-agent-log-level:
    type: string
    default: "dbg"
    description: "Log level for CP agent dbg,info"
  cp-package-url:
    default: "http://repohost/cplane_metadata.json"
    type: string
    description: |
      URL for cplane packages
      if from local repo then "http://xx.xx.xx.xx/cplane_metadata.json"
  metadata-shared-secret:
    type: string
    default:
    description: "Metadata shared secret"
  enable-unicast:
    default: False
    type: boolean
    description: "Flag to enable unicast"
  cplane-version:
    default: "1.3.8"
    type: string
    description: "Cplane softwares version"
  cp-vm-mtu:
    default: 1400
    type: int
    description: "MTU for vm-mtu interface"
  intf-mtu:
    default:
    type: string
    description: "MTU for node interface. Eg. br-ext=9000,eth0=9000"
  tso-flag:
    default:
    type: string
    description: "Flag to trun off the TSO for an interface. Eg. eth1.10=off,br-ext=off"
  gso-flag:
    default:
    type: string
    description: "Flag to trun off the GSO for an interface. Eg. eth1.10=off,br-ext=off"
