options:
  cplane-controller_ip:
    type: string
    default: "192.168.4.154"
    description: "IP of the Cplane controller"
  cplane-controller_port:
    type: int
    default: 8080
    description: "Cplane controller port"
  rabbit-user:
    type: string
    default: "neutron"
    description: "Neutron rabbit user name"
  rabbit-vhost:
    type: string
    default: "openstack"
    description: "Rabbit vhost"
  nova-database-user:
    type: string
    default: "neutron"
    description: "Neutron databse user"
  nova-database:
    type: string
    default: "neutron"
    description: "Neutron databasee"
  vlan-ranges:
    type: string
    default: "physnet1:1000:2000"
    description: |
      Space-delimited list of Neutron network-provider & vlan-id-ranges using
      the following format "<provider>:<start>:<end> ...".
  overlay-network-type:
    default: gre vxlan
    type: string
    description: |
      Overlay network types to use, valid options include:
        gre
        vxlan
      Multiple types can be provided - field is space delimited.
  security-groups:
    default: True 
    type: boolean
    description: Enable cplane  managed security groups.
  cp-package-url:
    default: "http://repohost/cplane_metadata.json"
    type: string
    description: |
      URL for cplane packages
      if from local repo then "http://xx.xx.xx.xx/cplane_metadata.json" 
  cplane-version:
    default: "1.3.8"
    type: string
    description: "Cplane softwares version"
  topology-name:
    default: "default"
    type: string
    description: "Name of the topology"
  intf-mtu:
    default:
    type: string
    description: "MTU for node interface. Eg. br-ext=9000,eth0=9000"
  tso-flag:
    default:
    type: string
    description: "Flag to trun off the TSO for an interface. Eg. eth1.10=off,br-ext=off"
  gso-flag:
    default:
    type: string
    description: "Flag to trun off the GSO for an interface. Eg. eth1.10=off,br-ext=off"
  rx-flag:
    default:
    type: string
    description: "Flag to trun off the RX for an interface. Eg. eth1.10=off,br-ext=off"
  tx-flag:
    default:
    type: string
    description: "Flag to trun off the TX for an interface. Eg. eth1.10=off,br-ext=off"
  sg-flag:
    default:
    type: string
    description: "Flag to trun off the SG for an interface. Eg. eth1.10=off,br-ext=off"
  ufo-flag:
    default:
    type: string
    description: "Flag to trun off the UFO for an interface. Eg. eth1.10=off,br-ext=off"
  gro-flag:
    default:
    type: string
    description: "Flag to trun off the GRO for an interface. Eg. eth1.10=off,br-ext=off"
  lro-flag:
    default:
    type: string
    description: "Flag to trun off the LRO for an interface. Eg. eth1.10=off,br-ext=off"
  openstack-version:
    default: "liberty"
    type: string
    description: "Openstack version eg. liberty, mitaka, ocata"
