#!/bin/bash
# Wrapper to deal with newer Ubuntu versions that don't have py2 installed
# by default.

declare -a DEPS=('apt' 'netifaces' 'ipaddr' 'netaddr')

check_and_install() {
    pkg="${1}-${2}"
    if ! yum list installed ${pkg} >/dev/null 2>&1; then
        yum -y install ${pkg}
    fi
}

PYTHON="python"

for dep in ${DEPS[@]}; do
    check_and_install ${PYTHON} ${dep}
done

exec ./hooks/install.real
