options:
  oracle-version:
    default: "oracle-xe"
    type: string
    description: "Version of oracle to be installed"
  controller-app-mode:
    default: "dvnd"
    type: string
    description: "The same installation can be use to install DVND(dvnd) as well as MSM(msm)"
  msm-version:
    default: 262
    type: int
    description: "Msm version to download"
  oracle-client-basic:
    default: "12"
    type: string
    description: "The oracle instant client basic version"
  oracle-sqlplus:
    default: "12"
    type: string
    description: "The oracle instant client sqlplus version"
  cp-package-url:
    default: "http://repohost/cplane_metadata.json"
    type: string
    description: |
      URL for cplane packages
      if from local repo then "http://xx.xx.xx.xx/cplane_metadata.json"
  oracle-http-port:
    default: "8085"
    type: string
    description: "Oracle Http port"
  oracle-listener-port:
    default: "1521"
    type: string
    description: "Oracle listener port"
  oracle-host:
    default: "localhost"
    type: string
    description: "Oracle host"  
  oracle-password:
    default: "password"
    type: string
    description: "Oracle password"
  db-user:
    default: "admin"
    type: string
    description: "Database  username"
  db-password:
    default: "admin"
    type: string
    description: "Database password"
  jboss-db-on-host:
    default: False
    type: boolean
    description: "Whether DB is on the same host where JBOSS is installed"
  oracle-db-enable:
    default: "y"
    type: string
    description: "Enable Oracle at boot time"  
  multicast-port:
    default: 1901
    type: int
    description: "Multicast port"
  multicast-intf:
    default: "br-eth2"
    type: string
    description: "Multicast Interface"
  unicast-port:
    default: 1902
    type: int
    description: "Unicast port"
  jboss-home:
    default: "/opt/jboss/jboss-6.1.0.Final"
    type: string
    description: "JBOSS_HOME path"
  intall-reboot-scripts:
    default: "y"
    type: string
    description: "Flag to install the reboot scripts"
  cplane-version:
    default: "1.3.8"
    type: string
    description: "Cplane softwares version"
  use-default-jboss-cluster:
    default: False
    type: boolean
    description: "Set y to use the default cluster else set n to use random cluster for each instance"
  jboss-cluster-name:
    default:
    type: string
    description: "Optional Jboss cluster name if the use-default-jboss-cluster is enable"
  enable-fip:
    default: False
    type: boolean
    description: "Flag to enable FIP interface"
  intf-mtu:
    default:
    type: string
    description: "MTU for node interface. Eg. br-ext=9000,eth0=9000"
  tso-flag:
    default:
    type: string
    description: "Flag to trun off the TSO for an interface. Eg. eth1.10=off,br-ext=off"
  gso-flag:
    default:
    type: string
    description: "Flag to trun off the GSO for an interface. Eg. eth1.10=off,br-ext=off"
  rx-flag:
    default:
    type: string
    description: "Flag to trun off the RX for an interface. Eg. eth1.10=off,br-ext=off"
  tx-flag:
    default:
    type: string
    description: "Flag to trun off the TX for an interface. Eg. eth1.10=off,br-ext=off"
  sg-flag:
    default:
    type: string
    description: "Flag to trun off the SG for an interface. Eg. eth1.10=off,br-ext=off"
  ufo-flag:
    default:
    type: string
    description: "Flag to trun off the UFO for an interface. Eg. eth1.10=off,br-ext=off"
  gro-flag:
    default:
    type: string
    description: "Flag to trun off the GRO for an interface. Eg. eth1.10=off,br-ext=off"
  lro-flag:
    default:
    type: string
    description: "Flag to trun off the LRO for an interface. Eg. eth1.10=off,br-ext=off"
  openstack-version:
    default: "liberty"
    type: string
    description: "Openstack version eg. liberty, mitaka, ocata"
  xe-db-process:
    default: 500
    type: int
    description: "Max processes for oracle XE DB"
  xe-db-ses-cach-cur:
    default: 200
    type: int
    description: "Max session_cached_cursors for oracle XE DB"
  xe-db-ses-max-op-file:
    default: 500
    type: int
    description: "Max session_max_open_files for oracle XE DB"
  xe-db-session:
    default: 500
    type: int
    description: "Max sessions for oracle XE DB"
  xe-db-lic-max-ses:
    default: 500
    type: int
    description: "Max license_max_sessions for oracle XE DB"
  xe-db-lic-ses-war:
    default: 500
    type: int
    description: "Warning limit for license_sessions_warning for oracle XE DB"
  production:
    default: "y"
    type: string
    description: "Flag to indicate the production deployment"
  # HA configuration settings
  dns-ha:
    type: boolean
    default: False
    description: |
        Use DNS HA with MAAS 2.0. Note if this is set do not set vip
        settings below.
  vip:
    type: string
    default:
    description: |
      Virtual IP(s) to use to front API services in HA configuration.

      If multiple networks are being used, a VIP should be provided for each
      network, separated by spaces.
  vip_iface:
    type: string
    default: eth0
    description: |
      Default network interface to use for HA vip when it cannot be
      automatically determined.
  vip_cidr:
    type: int
    default: 24
    description: |
      Default CIDR netmask to use for HA vip when it cannot be automatically
      determined.
  ha-bindiface:
    type: string
    default: eth0
    description: |
      Default network interface on which HA cluster will bind to communication
      with the other members of the HA Cluster.
  ha-mcastport:
    type: int
    default: 5434
    description: |
      Default multicast port number that will be used to communicate between
      HA Cluster nodes.
  haproxy-server-timeout:
    type: int
    default:
    description: |
      Server timeout configuration in ms for haproxy, used in HA
      configurations. If not provided, default value of 90000ms is used.
  haproxy-client-timeout:
    type: int
    default:
    description: |
      Client timeout configuration in ms for haproxy, used in HA
      configurations. If not provided, default value of 90000ms is used.
  haproxy-queue-timeout:
    type: int
    default:
    description: |
      Queue timeout configuration in ms for haproxy, used in HA
      configurations. If not provided, default value of 9000ms is used.
  haproxy-connect-timeout:
    type: int
    default:
    description: |
      Connect timeout configuration in ms for haproxy, used in HA
      configurations. If not provided, default value of 9000ms is used.
  jdk-version:
    type: int
    default: 0
    description: "Java version to download from Cplane repo"
